x-keycloak-common-env: &keycloak-common-env
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: password
  KC_LOG_CONSOLE_COLOR: 'true'

x-keycloak-common-extra: &keycloak-common-extra
  entrypoint: /bin/sh
  command:
    - -c
    - |
      set -ex
      cp /tmp/libs-*/keycloak-*.jar /opt/keycloak/providers
      /opt/keycloak/bin/kc.sh start-dev --import-realm
  volumes:
    - ./.docker/keycloak-config/:/opt/keycloak/data/import/:ro
    - ./target/:/tmp/libs-target:ro
  links:
    - prism

services:
  keycloak-21:
    image: quay.io/keycloak/keycloak:21.1.2
    ports:
      - '9021:9021'
    environment:
      <<: *keycloak-common-env
      KC_HTTP_PORT: 9021
    <<: *keycloak-common-extra
  
  keycloak-26:
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - '9026:9026'
    environment:
      <<: *keycloak-common-env
      KC_HTTP_PORT: 9026
    <<: *keycloak-common-extra

  # This is a mock server for the SMS API
  prism:
    image: stoplight/prism:latest
    ports:
      - "4010:4010"
    command:
      - mock
      - -h
      - 0.0.0.0
      - /openapi/sms-open-api.yml
    volumes:
      - ./openapi:/openapi
