openapi: 3.0.3
info:
  title: SMS OpenApi
  description: |
    Some existing API Server for sending POST message to help 
    with authentication at [https://bayamsell.com](https://pay.bayamsell.com)
  termsOfService: https://blog.ssegning.com
  contact:
    email: dev@ssegning.com
  license:
    name: MIT
  version: 1.0.0
externalDocs:
  description: Find out more about calling setting up an external service to verify phone number
  url: https://blog.ssegning.com
servers:
  - url: http://localhost:8080
    description: Dev server
  - url: https://sms-api-server:port
    description: Production server
tags:
  - name: sms
    description: All about sending an SMS
paths:
  /send-sms:
    post:
      tags:
        - sms
      summary: Send sms
      description: Send an SMS to the phone number provided
      operationId: sendSms
      security:
        - basic_auth: []
      requestBody:
        description: Send sms request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSmsRequest'
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendSmsResponse"
        default:
          description: successful operation
          content: {}

components:
  schemas:
    SendSmsRequest:
      type: object
      properties:
        phoneNumber:
          type: string
        smsCode:
          type: number
      required:
        - phoneNumber
        - smsCode
    SmsStatus:
      type: string
      enum:
        - SENT
        - ERROR
        - PENDING
    SendSmsResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/SmsStatus'
        description:
          type: string
          maxLength: 200
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
