openapi: 3.0.1
info:
  contact:
    email: hello@bayamsell.com
  description: BayamSell at [https://bayamsell.com](https://pay.bayamsell.com)
  license:
    name: MIT
  termsOfService: https://bayamsell.com/resources/terms-of-use
  title: Auth OpenApi
  version: 1.0.0
externalDocs:
  description: Find out more about ByS Pay
  url: https://bayamsell.com
servers:
- description: Dev server
  url: http://localhost:8080
- description: Production server
  url: http://backend:8080
tags:
- description: All about sending an SMS
  name: sms
paths:
  /{url}:
    post:
      description: Send an SMS to the phone number provided
      operationId: sendSms
      parameters:
      - description: Url of the sms api in the external server
        explode: false
        in: path
        name: url
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSmsRequest'
        description: Send sms request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendSmsResponse'
          description: successful operation
        default:
          content: {}
          description: successful operation
      security:
      - basic_auth: []
      summary: Send sms
      tags:
      - sms
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    SendSmsRequest:
      example:
        phoneNumber: phoneNumber
        smsCode: 0.8008281904610115
      properties:
        phoneNumber:
          type: string
        smsCode:
          type: number
      type: object
    SendSmsResponse:
      type: object
  securitySchemes:
    basic_auth:
      scheme: basic
      type: http

